[project]
name = "mi-script-gcs"
version = "0.1.0"
description = "Script Python usando Google Cloud Storage"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-storage>=2.16.0",
    "google-api-core>=2.15.0"
]

[tool.uv]
package = false
